# Djenesis/contributr
# travis-ci build file


# python3
language: python
python:
    - "3.3"
    - "3.4"

# cache pip packages for faster installs
cache:
    directories:
        - $HOME/.pip-cache/

# set environmental variables for project
env:
  matrix:
    # django
    - DJANGO_VERSION=1.8 DJANGO_SETTINGS_MODULE="contributr.settings.travis"

# install dependencies and any other requirements before running tests
install:
    # install dependencies for testing
    - pip install -r requirements/requirements_test.txt
    - pip install coveralls

# things to do before running tests
before-script:
    # apply migrations
    - python3 manage.py migrate

# run the test scripts
script:
    - cd contributr
    # run tests and measure test coverage
    - py.test --cov=.

# things to do if tests successfully halt
after_success:
    # send a signal for code coverage
    - coveralls

# notifications about test builds
notifications:
    slack: djenesis:pfQMEIxnzqPmfgvLLhkEsd1B
    on_sucess: always
    on_failure: always
